//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class FreelancerClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FreelancerClient()
        {
            this.Ratings = new HashSet<Rating>();
            this.Users = new HashSet<User>();
            this.Jobs = new HashSet<Job>();
        }
    
        public int freelancerID { get; set; }
        public string freelancerName { get; set; }
        public string freelancerSurname { get; set; }
        public string freelancerEmail { get; set; }
        public string freelancerPhone { get; set; }
        public string freelancerAddress { get; set; }
        public string city { get; set; }
        public string postalCode { get; set; }
        public string freelancerWebsite { get; set; }
        public string occupation { get; set; }
        public string bio { get; set; }
        public string imageURL { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job> Jobs { get; set; }
    }
}
