//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
        }
    
        public int jobCode { get; set; }
        public string jobDescription { get; set; }
        public Nullable<int> freelancerID { get; set; }
        public Nullable<decimal> hourlyRate { get; set; }
        public Nullable<decimal> baseRate { get; set; }
        public string imageURL { get; set; }
        public Nullable<System.DateTime> datePosted { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    
        public virtual FreelancerClient FreelancerClient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
