//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBox
    {
        public int messageID { get; set; }
        public string messageSubject { get; set; }
        public string messageBody { get; set; }
        public Nullable<int> creatorID { get; set; }
        public Nullable<System.DateTime> messageDate { get; set; }
        public Nullable<int> parentMessageID { get; set; }
    
        public virtual User User { get; set; }
    }
}
