//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Freelancer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int id { get; set; }
        public Nullable<int> freelancerID { get; set; }
        public Nullable<int> rating1 { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public string ipAddress { get; set; }
    
        public virtual FreelancerClient FreelancerClient { get; set; }
    }
}
